"""
Issue 2 - serve REAL model metrics instead of hardcoded numbers.

Reads what evaluate.py / ablation.py already write:
    outputs/metrics/ablation.json   (rows, selection, results[val|test][row])
    outputs/metrics/metrics.json    (meta: channels, reference product, event thresholds)
and returns exactly the shape the frontend's `ModelMetrics` type expects
(Frontend/src/types/index.ts).  Nothing is invented: a value that is missing is null.

Usage in backend/app.py:
    from metrics_loader import load_metrics
    @app.get("/api/metrics")
    def get_metrics():
        return load_metrics(REPO_ROOT / "outputs" / "metrics")
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Optional

BASELINE_ROW = "A"
# ablation.json keeps a few non-row keys (e.g. "B2 bias-corrected bilinear") in results
_ROW_LABEL_FALLBACK = {"B2 bias-corrected bilinear": "B2 bias-corrected bilinear"}


def _mae(res: dict, split: str, row: str) -> Optional[float]:
    v = res.get(split, {}).get(row, {}).get("MAE")
    return None if v is None else round(float(v), 3)


def load_layer1_manifest(metrics_dir: str | Path) -> Optional[dict]:
    """Provenance of the served Layer-1 grid (written by generate_pred.py).

    Lets the UI/API state WHICH models produced the rainfall field it is
    serving, and lets a mismatch against the metric files be detected instead
    of silently serving a stale field.
    """
    p = Path(metrics_dir) / "layer1_manifest.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except (OSError, ValueError):
        return None


def load_metrics(metrics_dir: str | Path) -> dict[str, Any]:
    d = Path(metrics_dir)
    ab_path, me_path = d / "ablation.json", d / "metrics.json"
    if not ab_path.exists():
        raise FileNotFoundError(f"{ab_path} missing - run scripts/ablation.py first")
    ab = json.loads(ab_path.read_text())
    meta = json.loads(me_path.read_text()).get("meta", {}) if me_path.exists() else {}
    layer1 = load_layer1_manifest(d)

    rows, res, sel = ab["rows"], ab["results"], ab["selection"]
    label = lambda k: rows.get(k, {}).get("label", _ROW_LABEL_FALLBACK.get(k, k))

    def variants(split: str) -> list[dict]:
        out = []
        for k, r in res.get(split, {}).items():
            out.append({"split": split, "model": label(k), "MAE_mm": round(float(r["MAE"]), 3),
                        "RMSE_mm": round(float(r["RMSE"]), 3), "corr": round(float(r["corr"]), 4)})
        return out

    test_v, val_v = variants("test"), variants("val")
    row = sel["row"]
    sel_mae, base_mae = _mae(res, "test", row), _mae(res, "test", BASELINE_ROW)
    sel_test = res.get("test", {}).get(row, {})
    improvement = (round(100 * (base_mae - sel_mae) / base_mae, 1)
                   if sel_mae is not None and base_mae else None)

    test_dates = meta.get("split", {}).get("test", {}).get("dates", [])
    period = f"{test_dates[0]} to {test_dates[-1]} (monsoon test season)" if test_dates else "test split"

    return {
        "all_variants": val_v + test_v,
        "test_variants": test_v,
        "selected_model": {
            "name": sel.get("label", label(row)),
            "variant_key": row,
            "test_mae_mm": sel_mae,
            "test_rmse_mm": None if not sel_test else round(float(sel_test["RMSE"]), 3),
            "test_correlation": None if not sel_test else round(float(sel_test["corr"]), 4),
        },
        "baseline": {"name": label(BASELINE_ROW), "test_mae_mm": base_mae},
        "mae_improvement_pct": improvement,
        "evaluation_period": period,
        "reference_product": "CHIRPS v2.0",
        "reference_note": meta.get("reference", "CHIRPS is a reference product, not ground truth"),
        "channels": meta.get("channels", []),
        "n_parameters": "n/a",   # filled by live_infer.ModelRunner.n_parameters when torch is present
        # extra, honest detail the UI can show: heavy-rain skill
        "event_f1_test": {
            thr: {"model": sel_test.get(f">={thr}mm", {}).get("F1"),
                  "baseline": res["test"].get(BASELINE_ROW, {}).get(f">={thr}mm", {}).get("F1")}
            for thr in ("10", "25", "50")
        },
        # Which models actually produced outputs/prediction_test.npz, with their
        # hashes. None when the grid was never generated by generate_pred.py.
        "layer1_provenance": None if layer1 is None else {
            "generated_at_utc": layer1.get("generated_at_utc"),
            "grid": layer1.get("artefact", {}).get("path"),
            "grid_sha256": layer1.get("artefact", {}).get("sha256"),
            "dates": [layer1.get("geometry", {}).get("first_date"),
                      layer1.get("geometry", {}).get("last_date")],
            "max_mm": layer1.get("values", {}).get("max_mm"),
            "mean_mm": layer1.get("values", {}).get("mean_mm"),
            "finite_cells_per_day": layer1.get("values", {}).get("finite_cells_per_day"),
            "members": layer1.get("predictor", {}).get("members"),
            "weights": layer1.get("predictor", {}).get("weights"),
            "checkpoint_sha256": layer1.get("predictor", {}).get("checkpoint_sha256"),
        },
    }
